application: greatshipgroup
version: development
runtime: python
api_version: 1

default_expiration: "7d"

handlers:
- url: /s
  static_dir: public
  secure: never
  expiration: 10s

- url: /favicon.ico
  static_files: public/image/icon/favicon.png
  upload: public/image/icon/favicon.png
  secure: never

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  expiration: 7d
  secure: never

- url: /console/static/
  static_dir: console/app/view/static
  expiration: 7d

- url: /console.*
  script: console/app/console.py
  login: admin

- url: /.*
  script: handlers.py

skip_files: |
  ^(.*/)?(
  (app\.yaml)|
  (app\.yml)|
  (index\.yaml)|
  (index\.yml)|
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*\.bak)|
  (.*\.gitignore)|
  (\..*)
  )$
